<?php

namespace MsCom\WebsiteBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class StartController__JMSInjector
{
    public static function inject($container) {
        $instance = new \MsCom\WebsiteBundle\Controller\StartController();
        return $instance;
    }
}
